update to new react-native-mp-android-chart base on mpAndroidChart V3
mskec/react-native-mp-android-chart-example pull request #5
Opened 2017-02-19 05:40 UTC by wuxudong

update to new react-native-mp-android-chart base on mpAndroidChart V3

2017-02-25 23:28 UTC, mskec requested changes
Thanks for updating example.

I made some screenshots with some problems I discovered http://imgur.com/a/qXjbg. In image description you can see what is not like before. If you download current .apk from this repo you can see how it was before.

Additionally BubbleChart, animations are not working as before. Do you know why? Also default zoom is little different.

2017-02-25 23:28 UTC, mskec commented on app/BubbleChartScreen.js
> +    return _.times(size, (index) => {
index is not used

2017-02-25 23:28 UTC, mskec commented on package.json
> +    "react-native": "^0.41.2",
Please lock vesrsions

2017-03-02 08:52 UTC, wuxudong commented
for the bar chart, additional config required.

 granularityEnabled:true,
 granularity:1

I will update examples later

2017-03-05 14:04 UTC, wuxudong commented
update again.

Because it depends on react-native-mp-android-chart whose pr is under review. you should update the package.json 

`"react-native-mp-android-chart": "file:../react-native-mp-android-chart/"` to test it.

if react-native-mp-android-chart‘s new version is released, then you can update it to correct version number.

2017-03-06 09:22 UTC, mskec reviewed
Could you update BarChart with additional config so that it's the same as before?

2017-03-06 09:22 UTC, mskec commented on app/TimeSeriesLineChartScreen.js
> +          // labels: ['REFER', 'USER',]
what about this?

2017-03-06 09:22 UTC, mskec commented on app/TimeSeriesLineChartScreen.js
> +                drawCubic: true,
update to `mode`

2017-03-06 22:10 UTC, merged